# Generated by Django 4.0.5 on 2022-06-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_tech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preinscription',
            old_name='module',
            new_name='modules',
        ),
    ]
