# Generated by Django 4.0.5 on 2022-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
